import {
    Building2,
    Users,
    Briefcase,
    Calendar,
    Gift,
    MapPin,
    Clock
} from 'lucide-react';

export const setupSteps = [
    { id: 'company', label: 'Company Info', icon: Building2 },
    { id: 'departments', label: 'Departments', icon: Users },
    { id: 'positions', label: 'Job Positions', icon: Briefcase },
    { id: 'leave', label: 'Leave Types', icon: Calendar },
    { id: 'benefits', label: 'Benefits', icon: Gift },
    { id: 'employment', label: 'Employment Types', icon: Users },
    { id: 'locations', label: 'Work Locations', icon: MapPin },
    { id: 'holidays', label: 'Holidays', icon: Calendar },
    { id: 'shifts', label: 'Work Shifts', icon: Clock },
];

export const defaultSetupData = {
    companyName: 'Acme Corporation',
    companyMission: 'To empower businesses with innovative technology solutions that drive growth and success.',
    companyVision: 'To be the leading provider of enterprise solutions, transforming how organizations operate and grow in the digital age.',
    registrationNumber: 'REG-2024-12345',
    taxId: '12-3456789',
    foundedYear: '2010',
    industry: 'Technology',
    companySize: '100-500',
    website: 'www.acmecorp.com',
    primaryEmail: 'info@acmecorp.com',
    phoneNumber: '+1 (555) 123-4567',
    address: '123 Business Street',
    city: 'San Francisco',
    state: 'California',
    postalCode: '94102',
    country: 'United States',
    departments: [
        { id: '1', name: 'Engineering', description: 'Software development and technical operations' },
        { id: '2', name: 'Marketing', description: 'Brand management and customer engagement' },
        { id: '3', name: 'Sales', description: 'Revenue generation and client relations' },
        { id: '4', name: 'Human Resources', description: 'Employee management and organizational development' },
        { id: '5', name: 'Finance', description: 'Financial planning and accounting' },
    ],
    positions: [
        { id: '1', title: 'Software Engineer', department: 'Engineering', level: 'Mid-Level' },
        { id: '2', title: 'Senior Software Engineer', department: 'Engineering', level: 'Senior' },
        { id: '3', title: 'Marketing Manager', department: 'Marketing', level: 'Manager' },
        { id: '4', title: 'Sales Representative', department: 'Sales', level: 'Entry' },
        { id: '5', title: 'HR Manager', department: 'Human Resources', level: 'Manager' },
    ],
    leaveTypes: [
        { id: '1', name: 'Annual Leave', defaultDays: 15, requiresApproval: true },
        { id: '2', name: 'Sick Leave', defaultDays: 10, requiresApproval: false },
        { id: '3', name: 'Personal Leave', defaultDays: 5, requiresApproval: true },
        { id: '4', name: 'Maternity Leave', defaultDays: 90, requiresApproval: true },
        { id: '5', name: 'Paternity Leave', defaultDays: 14, requiresApproval: true },
    ],
    benefitTypes: [
        { id: '1', name: 'Health Insurance', category: 'Health', description: 'Comprehensive health coverage' },
        { id: '2', name: 'Dental Insurance', category: 'Health', description: 'Dental care coverage' },
        { id: '3', name: '401(k) Match', category: 'Retirement', description: 'Company 401k matching' },
        { id: '4', name: 'Life Insurance', category: 'Insurance', description: 'Life insurance coverage' },
        { id: '5', name: 'Gym Membership', category: 'Wellness', description: 'Fitness center access' },
    ],
    employmentTypes: [
        { id: '1', name: 'Full-Time', description: 'Regular full-time employment' },
        { id: '2', name: 'Part-Time', description: 'Part-time employment' },
        { id: '3', name: 'Contract', description: 'Fixed-term contract' },
        { id: '4', name: 'Intern', description: 'Internship position' },
        { id: '5', name: 'Consultant', description: 'External consultant' },
    ],
    workLocations: [
        { id: '1', name: 'Headquarters', address: '123 Main St, New York, NY', isRemote: false },
        { id: '2', name: 'West Coast Office', address: '456 Tech Ave, San Francisco, CA', isRemote: false },
        { id: '3', name: 'Remote', address: 'Various Locations', isRemote: true },
    ],
    holidays: [
        { id: '1', name: 'New Year\'s Day', date: '2025-01-01', type: 'Public' },
        { id: '2', name: 'Independence Day', date: '2025-07-04', type: 'Public' },
        { id: '3', name: 'Thanksgiving', date: '2025-11-27', type: 'Public' },
        { id: '4', name: 'Christmas', date: '2025-12-25', type: 'Public' },
        { id: '5', name: 'Company Anniversary', date: '2025-03-15', type: 'Company' },
    ],
    workShifts: [
        { id: '1', name: 'Morning Shift', startTime: '06:00', endTime: '14:00', description: 'Early morning operations' },
        { id: '2', name: 'Day Shift', startTime: '09:00', endTime: '17:00', description: 'Standard business hours' },
        { id: '3', name: 'Evening Shift', startTime: '14:00', endTime: '22:00', description: 'Afternoon and evening coverage' },
        { id: '4', name: 'Night Shift', startTime: '22:00', endTime: '06:00', description: 'Overnight operations' },
    ],
};